### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Odyssey346** [jtaczanowski/ThinkPad-X201-Arrandale-macOS-OpenCore#2]
Hi, I've installed Big Sur on my X201 through this guide. After rebooting from the installer, my screen is a blinking cursor. What do I do to fix this? Do I have to wait? Because on my UEFI patched OpenCore install USB it was lightning fast to show something, so I wouldn't think it'd be slower on a sata ssd.

**Comment by jtaczanowski** [comment]
Hi :)
Did you install OpenCore on your sata SSD? To boot from sata SSD you have to install OpenCore on it after BigSur instalation process. So, for the first system boot - after installation, you should use OpenCore from your USB drive, boot BigSur and install OpenCore on your SATA ssd.

**Comment by Odyssey346** [comment]
Is it an option in the OpenCore bootloader or something? I don't really understand

**Comment by Odyssey346** [comment]
Ok, I read a bit, I'll try again later

**Comment by jtaczanowski** [comment]
Install OpenCore on sata ssd in the same way like on your installation pendrive - this is exactly the same procedure.

**Comment by Odyssey346** [comment]
Hmm, I did do that but, well, OpenCore legacy boot patcher doesn't work in macOS recovery. Do I just copy all the files from my USB over to the efi partition?

**Comment by Odyssey346** [comment]
I see that I can go into macOS installer from the opencore usb i have, but my usb keyboard wont work in it too. I guess I can try another USB keyboard I have...

**Comment by Odyssey346** [comment]
Great, I found a USB keyboard that works :) Too bad it's my dad's keyboard...

**Comment by Odyssey346** [comment]
Ok, everything works now :D

**Comment by jtaczanowski** [comment]
@Odyssey346 nice to hear that everything works :) Did you change SystemProductName to MacBookPro6,2 to achieve full CPU speeds?

**Comment by Odyssey346** [comment]
Yeah, I did.
