### ISSUE TITLE
Trouble with HfsPlusLegacy.efi

### ISSUE THREAD

**Issue by fajnykod** [jtaczanowski/ThinkPad-X201-Arrandale-macOS-OpenCore#24]
Hi,

I'm trying to install this on a Lenovo Thinkpad X201 i5-540m, I have done this in the past and it had worked but now when I make a USB the same way as in the guide it won't boot into the installer, says something like HfsPlusLegacy.efi at 3 - unsupported! I have tried to just skip the file by making it false in the config.plist and it boots but just hangs at some text with # at the start. What's going on here and how can I fix this? 

(I am using the latest OpenCore release 0.8.8-RELEASE and a cloned version of this repo if that helps.)

Thanks! (Log here: [opencore-2023-01-03-160918.txt](https://github.com/jtaczanowski/ThinkPad-X201-Arrandale-macOS-OpenCore/files/10338445/opencore-2023-01-03-160918.txt))

**Comment by Scorpionchiques** [comment]
> Hi,
> 
> I'm trying to install this on a Lenovo Thinkpad X201 i5-540m, I have done this in the past and it had worked but now when I make a USB the same way as in the guide it won't boot into the installer, says something like HfsPlusLegacy.efi at 3 - unsupported! I have tried to just skip the file by making it false in the config.plist and it boots but just hangs at some text with # at the start. What's going on here and how can I fix this?
> 
> (I am using the latest OpenCore release 0.8.8-RELEASE and a cloned version of this repo if that helps.)
> 
> Thanks! (Log here: [opencore-2023-01-03-160918.txt](https://github.com/jtaczanowski/ThinkPad-X201-Arrandale-macOS-OpenCore/files/10338445/opencore-2023-01-03-160918.txt))

You shuld use opencore from this repo 0.8.0

**Comment by fajnykod** [comment]
Thanks! I'll test it out once I install the tools to make the OpenCore USB again.

**Comment by fajnykod** [comment]
Using the 0.8.0 version of OpenCore fixed the issue with booting! Since I no longer have this issue I'll close this.
