### ISSUE TITLE
graphics QE/CI acceleration not working

### ISSUE THREAD

**Issue by rivciks** [jtaczanowski/ThinkPad-X201-Arrandale-macOS-OpenCore#27]
Hello,
I have a Thinkpad t410 but my graphics card is the same as in your model: Intel HD Graphics 288 MB.

I did everything as described and also ran OpenCore-Patcher and applied the Post Install Root Patch. The system was patched, as I am able to tell,  sucessfully without errors; but it seems that the  QE/CI acceleration is not working.  Everything runs really slow and the VDADecoderCheck also fails.

P.S. Everything else seems to be working on Big Sur, except for the  brightess keys, they do not work and there is no brighness slider either or other tool that makes brightness changeable  and that is pretty inconvenient since the default setting for display brightness on MacOS is rather pretty  dim. 

![Screenshot 2023-07-06 at 17 04 36](https://github.com/jtaczanowski/ThinkPad-X201-Arrandale-macOS-OpenCore/assets/122794453/ed444972-df6b-4ce6-b627-709ccc7d1d8f)
![Screenshot 2023-07-06 at 17 13 18](https://github.com/jtaczanowski/ThinkPad-X201-Arrandale-macOS-OpenCore/assets/122794453/c08f27a2-10ad-44e7-95d3-7386a6194a0b)

**Comment by jtaczanowski** [comment]
Hi :)
Have you checked if this issue existing also in Monterey installation?
Maybe there is differences between x201 and t410. From what I remember I have made some changes in this section of `config.plist` file:
https://github.com/jtaczanowski/ThinkPad-X201-Arrandale-macOS-OpenCore/blob/main/EFI/OC/config.plist#L361:L388
to get iGPU working correctly with post install patches.
One of instructions on which I based was this manual: https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md

**Comment by rivciks** [comment]
Thanx,  
After further examination it seems that QE/CI acceleration is actually working despite failed DADecoderCheck.
