### ISSUE TITLE
CPU Power Management with Speedstep

### ISSUE THREAD

**Issue by rivciks** [jtaczanowski/ThinkPad-X201-Arrandale-macOS-OpenCore#28]
Hello again, 
I have also a question: how do you enable the Intel CPU speedstep on the Thinkpad? Do you have to download a special tool or something like that?

P.S. Thanx for the guide. 👍

**Comment by jtaczanowski** [comment]
To enable speedstep I have to patch/spoof LPC device-id `pci8086,3b07` -> `pci8086,3b09` to match LPC device-id from real MacBookPro6,2 `https://github.com/jtaczanowski/ThinkPad-X201-Arrandale-macOS-OpenCore#information-about-cpu-power-management-intel-speedstep
I used MaciASL tool to patch this LPC device-id.
More detailed informations about patching process I described here:
https://github.com/jtaczanowski/ThinkPad-X201-Arrandale-macOS-OpenCore/issues/4#issuecomment-899125408

**Comment by rivciks** [comment]
OK. Thank You.
