### ISSUE TITLE
Can this work on a thinkpad x301?

### ISSUE THREAD

**Issue by iddu0** [jtaczanowski/ThinkPad-X201-Arrandale-macOS-OpenCore#35]
Can it?

**Comment by jtaczanowski** [comment]
I don't think so, at least not without modification - this is older device then x201. Thinkpad x201 has i series CPU, x301 has core2duo series cpu.

**Comment by iddu0** [comment]
Sorry to bother you, but what would I modify in the EFI or other folders?
Thanks for the help!
